apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: JDBC-v4.3
  title: JDBC-v4.3a
  description: JDBC provides client access to databases from Java
  tags: 
    - java
    - db
    - client
  annotations:
    github.com/project-slug: mark-dutra/mark-demo
  links:
  - url: https://www.oracle.com/database/technologies/appdev/jdbc-downloads.html
    title: JDBC Information Page
  - url: http://tap-gui.tkgi-apps.wnp.polaris.cvshealthcloud.com/catalog/default/component/sample-asset
    title: Previous version
spec:
  type: library
  lifecycle: production
  owner: devsecops
  system: java
  

